connect21/community/urls.py
from django.urls import path

from .views import PublicProfileView, UserCommunityView, invite_user

app_name = 'community'

urlpatterns = [
    path('search/', UserCommunityView.as_view(), name='search'),
    path('@<str:username>/', PublicProfileView.as_view(), name='public-user-profile'),
    path('', UserCommunityView.as_view(), name='community-list'),
    path('invite/<int:user_id>/<int:group_id>/', invite_user, name='invite_user')

]

connect21/connect21/urls.py
from django.conf.urls import handler404
from django.contrib import admin
from django.urls import include, path

handler404 = 'main.views.page_not_found'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('community/', include('community.urls')),
    path('groups/', include('groups.urls'))

]

connect21/groups/urls.py
from django.urls import path

from .views import CreateGroupView, DeleteChatView, chat_view

app_name = 'groups'

urlpatterns = [
    path('chat/<uuid:group_uuid>/', chat_view, name='group_chat'),
    path('create/', CreateGroupView.as_view(), name='create_chat'),
    path('delete/<uuid:uuid>/', DeleteChatView.as_view(), name='delete_chat'),

]

connect21/main/urls.py
from django.urls import path

from .views import AboutView, HomeView, RespondInvitationView

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    path('invite/respond/<int:invitation_id>/', RespondInvitationView.as_view(), name='respond_invitation'),
]

connect21/main/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views import View
from django.views.generic import TemplateView

from groups.models import GroupInvitation, GroupMembership
from main.mixins import TitleMixin


class HomeView(TitleMixin, TemplateView):
    title = 'Connect21 - Главная'
    template_name = 'main/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['user_groups'] = GroupMembership.objects.filter(user=self.request.user).select_related('group')
            context['incoming_invitations'] = GroupInvitation.objects.filter(receiver=self.request.user, status='pending')
            context['show_create_chat_button'] = True
        return context


class RespondInvitationView(LoginRequiredMixin, View):
    def post(self, request, invitation_id):
        invitation = get_object_or_404(GroupInvitation, id=invitation_id)

        response = request.POST.get('response')
        if response == 'accept':
            invitation.status = 'accepted'
            invitation.save()
            GroupMembership.objects.create(
                user=request.user,
                group=invitation.group
            )
            messages.success(request, "Приглашение принято!")
        elif response == 'decline':
            invitation.status = 'declined'
            invitation.save()
            messages.info(request, "Приглашение отклонено.")

        return HttpResponseRedirect(request.META['HTTP_REFERER'])


def page_not_found(request, exception):
    return render(request, '404.html', status=404, context={'title': 'Connect21 - Страница не найдена'})


class AboutView(TitleMixin, TemplateView):
    title = 'Connect21 - О нас'
    template_name = 'main/about.html'

connect21/main/templates/main/about.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'deps/css/main_page.css' %}">
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="main-card text-center rounded-3 shadow">
                    <div class="main-card-body">
                        <h1 class="animated-title">О Connect21</h1>
                        <p class="main-card-text">
                            Connect21 — это платформа, предназначенная для объединения людей с общими интересами.
                            Наша цель — создать сообщество, где пользователи могут находить единомышленников,
                            обмениваться знаниями и опытом, а также участвовать в интересных групповых мероприятиях.
                        </p>
                        <p class="main-card-text">
                            Мы предлагаем различные инструменты для поиска пользователей и создания групп по интересам,
                            что позволяет делиться опытом и получать новые знания. Платформа также поддерживает
                            обмен сообщениями, что делает общение более доступным и удобным.
                        </p>
                        <p class="main-card-text">
                            Наши пользователи имеют возможность настраивать свои профили, делиться интересами и находить
                            людей, с которыми их связывают общие хобби и цели. Мы верим, что вместе мы можем
                            достичь большего, и мы рады приветствовать вас в нашем сообществе.
                        </p>
                        <p class="main-card-text">
                            Присоединяйтесь к нам, чтобы делиться опытом, находить поддержку и вдохновение в общении
                            с единомышленниками!
                        </p>
                        <div class="text-center main-card-text">
                            <p>
                                Made with ❤️ by <a href="https://github.com/agapoov" target="_blank">Zakhryapa</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

connect21/main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'deps/css/main_page.css' %}">
{% endblock %}

{% block content %}
    <a href="{% url 'community:community-list' %}" class="btn btn-primary_custom ">Перейти в список</a>
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="main-card text-center rounded-3 shadow">
                    <div class="main-card-body">
                        <h1 class="animated-title">Добро пожаловать в Connect21!</h1>
                        <p class="main-card-text">
                            Здесь вы можете найти пользователей, обмениваться информацией и создавать группы по интересам.
                            Присоединяйтесь к сообществу, чтобы делиться опытом и получать новые знания.
                        </p>
                        <a href="{% url 'main:about' %}" class="btn btn-primary_custom">Узнать больше</a>
                    </div>
                </div>

                <div class="container mt-4">
                    <div class="row justify-content-center">
                        <div class="col-lg-8">
                            <div class="main-card text-center rounded-3 shadow">
                                <div class="main-card-body">
                                    {% if request.user.is_authenticated %}
                                        <h2 class="animated-title mb-4 text-primary">Ваши чаты</h2>
                                        {% if user_groups %}
                                            <div class="group-cards">
                                                {% for membership in user_groups %}
                                                    <div class="group-card rounded-3 shadow-sm p-3 mb-3">
                                                        <h5 class="group-name">{{ membership.group.name }}</h5>
                                                        <a href="{% url 'groups:group_chat' membership.group.uuid %}" class="btn group_main_button">Перейти</a>
                                                    </div>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            <p class="main-card-text text-muted">У вас пока нет чатов.</p>
                                        {% endif %}
                                    {% else %}
                                        <p class="main-card-text text-muted">Войдите в аккаунт, чтобы вас могли пригласить в чат.</p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>



                <div class="main-card-text mt-4">
                    {% if incoming_invitations.count > 0 %}
                        <h2>Входящие приглашения</h2>
                        <ul class="list-group_revievs">
                            {% for invitation in incoming_invitations %}
                                <li class="list-group-item">
                                    Вы получили приглашение от {{ invitation.sender.username }} в группу "{{ invitation.group.name }}"!
                                    <form method="POST" action="{% url 'main:respond_invitation' invitation.id %}" style="display:inline;">
                                        {% csrf_token %}
                                        <button type="submit" name="response" value="accept" class="btn btn-success btn-sm">Принять</button>
                                        <button type="submit" name="response" value="decline" class="btn btn-danger btn-sm">Отклонить</button>
                                    </form>
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}