connect21/connect21/urls.py
from django.conf.urls import handler404
from django.contrib import admin
from django.urls import include, path

handler404 = 'main.views.page_not_found'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('community/', include('community.urls')),
    path('groups/', include('groups.urls'))

]

connect21/main/urls.py
from django.urls import path

from .views import AboutView, HomeView, RespondInvitationView

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    path('invite/respond/<int:invitation_id>/', RespondInvitationView.as_view(), name='respond_invitation'),
]

connect21/users/urls.py
from django.urls import path

from .views import (CustomLoginView, CustomLogoutView, CustomProfileView,
                    CustomRegisterView, TwoFactorAuthView, forgot_password)

app_name = 'users'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', CustomRegisterView.as_view(), name='register'),
    path('profile/', CustomProfileView.as_view(), name='profile'),
    path('two-factor-auth/<uuid:uuid>', TwoFactorAuthView.as_view(), name='two-factor-auth'),
    path('forgot-password/', forgot_password, name='forgot-password'),
    path('logout/', CustomLogoutView.as_view(), name='logout')
]

connect21/users/models.py
import random

from django.contrib.auth.models import AbstractUser
from django.db import models

from .tasks import send_two_factor_code_email_task


class User(AbstractUser):
    GENDER_CHOICES = [
        ('M', 'Мужской'),
        ('F', 'Женский')
    ]
    surname = models.CharField(max_length=128)
    tg_username = models.CharField(max_length=128)
    age = models.IntegerField(default=0)
    email = models.EmailField(unique=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    interests = models.CharField(max_length=128, null=True, blank=True)
    additional_info = models.CharField(max_length=512, null=True, blank=True)

    def __str__(self):
        return self.username

    @staticmethod
    def generate_code():
        code = random.randint(100000, 999999)
        return code

    def send_verification_email(self, code):
        subject = f'Код подтверждения для {self.username}'
        message = (
            f'Ваш код подтверждения: {code}\n'
            'С уважением, команда School21'
        )
        send_two_factor_code_email_task.delay(subject, message, self.email)

connect21/users/forms.py
from datetime import datetime, timedelta

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.utils import timezone

from connect21.settings import CODE_LIFETIME_MINUTES

from .models import User


class CustomUserLoginForm(AuthenticationForm):
    username = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Имя пользователя'
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label='Пароль'
    )


class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Имя'
    )
    last_name = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Фамилия'
    )
    surname = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Отчество',
    )
    gender = forms.ChoiceField(
        choices=[('M', 'Мужской'), ('F', 'Женский')],
        widget=forms.Select(attrs={'class': 'form-control'}),
        label='Пол'
    )
    age = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control'}),
        label='Возраст'
    )
    tg_username = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Ник в @Telegram'
    )
    username = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Имя пользователя'
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
        label='Электронная почта'
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label='Пароль',
        required=True
    )
    password2= forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label='Подтверждение пароля',
        required=True
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'surname', 'gender', 'age', 'tg_username', 'username',
                  'email', 'password1', 'password2']



class TwoFactorLoginForm(forms.Form):
    code = forms.IntegerField(label='Код подтверждения')

    def clean_code(self):
        code = self.cleaned_data.get('code')
        timestamp_str = self.initial.get('timestamp')

        if not timestamp_str:
            raise forms.ValidationError('Время начала сессии не найдено. Попробуйте войти снова.')

        timestamp = datetime.strptime(timestamp_str, '%Y-%m-%d %H:%M:%S')
        timestamp = timezone.make_aware(timestamp, timezone.get_current_timezone())

        if (timezone.now() - timestamp) > timedelta(minutes=CODE_LIFETIME_MINUTES):
            raise forms.ValidationError('Код истек. Войдите заново.')

        if not code or len(str(code)) != 6:
            raise forms.ValidationError('Код должен состоять из 6 цифр.')

        return code


class CustomUserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'surname', 'gender', 'age', 'tg_username', 'username', 'email', 'interests', 'additional_info']
        widgets = {
            'interests': forms.Textarea(attrs={'rows': 4, 'cols': 40, 'oninput': 'autoResize(this)', 'maxlength': '128'}),
            'additional_info': forms.Textarea(attrs={'rows': 6, 'cols': 40, 'oninput': 'autoResize(this)', 'maxlength': '512'}),
            'email': forms.EmailInput(attrs={'readonly': 'readonly'})
        }

connect21/users/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView
from django.views.generic.edit import FormView

from main.mixins import TitleMixin

from .forms import (CustomUserCreationForm, CustomUserLoginForm,
                    CustomUserProfileForm, TwoFactorLoginForm)
from .mixins import UserVerificationMixin
from .models import User


class CustomLoginView(TitleMixin, UserVerificationMixin, LoginView):
    template_name = 'users/login.html'
    authentication_form = CustomUserLoginForm
    title = 'Connect21 - Вход'
    success_url = reverse_lazy('main:index')

    def form_valid(self, form):
        user = form.get_user()
        verification_uuid = self.handle_verification(user)
        return redirect('users:two-factor-auth', uuid=verification_uuid)

    def form_invalid(self, form):
        messages.warning(self.request, 'Неверный Юзернейм или пароль.')
        return super().form_invalid(form)


class CustomRegisterView(TitleMixin, UserVerificationMixin, CreateView):
    template_name = 'users/registration.html'
    form_class = CustomUserCreationForm
    title = 'Connect21 - Регистрация '
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        verification_uuid = self.handle_verification(user)
        return redirect('users:two-factor-auth', uuid=verification_uuid)


class TwoFactorAuthView(TitleMixin, FormView):
    title = 'Connect - 2FA Auth'
    form_class = TwoFactorLoginForm
    template_name = 'users/two_factor_auth.html'

    def get_initial(self):
        return {'uuid': self.kwargs['uuid'], 'timestamp': self.request.session.get('timestamp')}

    def form_valid(self, form):
        code = form.cleaned_data['code']

        if str(code) == str(self.request.session.get('two_factor_code')):
            user_id = self.request.session.get('user_id')
            try:
                user = User.objects.get(id=user_id)
            except User.DoesNotExist:
                form.add_error(None, 'Пользователь не найден.')
                return self.form_invalid(form)

            login(self.request, user)
            messages.success(self.request, 'Добро пожаловать')

            self._clear_session()
            return super().form_valid(form)

        form.add_error(None, 'Неверный код')
        return self.form_invalid(form)

    def _clear_session(self):
        keys_to_clear = ['two_factor_code', 'user_id', 'verification_uuid']
        for key in keys_to_clear:
            self.request.session.pop(key, None)

    def get_success_url(self):
        return reverse('main:index')


class CustomProfileView(TitleMixin, LoginRequiredMixin, UpdateView):
    model = User
    title = 'Connect21 - Редактирование профиля'
    template_name = 'users/profile.html'
    form_class = CustomUserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        user = form.save(commit=False)
        user.save()
        messages.success(self.request, 'Профиль успешно обновлен')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, 'Произошла ошибка')
        return super().form_invalid(form)


def forgot_password(request):
    return render(request, 'users/forgot_password.html')


class CustomLogoutView(LogoutView):
    def get_success_url(self):
        messages.success(self.request, 'Вы вышли из аккаунта')
        return reverse_lazy('main:index')

connect21/users/templates/users/forgot_password.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        <p class="text-white text-center">Не забывайте.</p>
    </head>
    <body>

    </body>
{% endblock %}

connect21/users/templates/users/login.html
<!doctype html>
<html lang="en">

{% load static %}

<link rel="icon" href="{% static 'deps/images/favicon.svg' %}" type="image/x-icon">
<link rel="stylesheet" href="{% static 'deps/css/login_css.css' %}">
<title>{{ title }}</title>
<div class="container">
    <div class="login-box">
        <h2>Вход</h2>
        <form method="post" action="{% url 'users:login' %}">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="input-box">
                {{ form.username }}
                <label for="{{ form.username.id_for_label }}">Юзернейм</label>
                {{ form.username.errors }}
            </div>
            <div class="input-box">
                {{ form.password }}  <!-- Поле для пароля -->
                <label for="{{ form.password.id_for_label }}">Пароль</label>
                {{ form.password.errors }}  <!-- Ошибки для поля пароля -->
            </div>
            <div class="forgot-pass">
                <a href="{% url 'users:forgot-password' %}">Забыли пароль?</a>
            </div>
            <button type="submit" class="btn">Войти</button>
            <div class="signup-link">
                <a href="{% url 'users:register' %}">Зарегистрироваться</a>
            </div>
        </form>
    </div>
</div>

</html>

connect21/users/templates/users/profile.html
<!doctype html>
<html lang="en">

{% load static %}
<link rel="icon" href="{% static 'deps/images/favicon.svg' %}" type="image/x-icon">
<link rel="stylesheet" href="{% static 'deps/css/register_css.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
<title>{{ title }}</title>
<div class="container">
    <div class="login-box">
        <a href="{% url 'main:index' %}" class="btn back-btn">
            <i class="fas fa-arrow-left"></i> Вернуться
        </a>
        <h2>Профиль пользователя</h2>
        <form method="post" action="{% url 'users:profile' %}">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="input-row">
                <div class="input-box">
                    {{ form.first_name }}
                    <label for="{{ form.first_name.id_for_label }}">Имя</label>
                    {{ form.first_name.errors }}
                </div>
                <div class="input-box">
                    {{ form.last_name }}
                    <label for="{{ form.last_name.id_for_label }}">Фамилия</label>
                    {{ form.last_name.errors }}
                </div>
            </div>
            <div class="input-row">
                <div class="input-box">
                    {{ form.surname }}
                    <label for="{{ form.surname.id_for_label }}">Отчество</label>
                    {{ form.surname.errors }}
                </div>
                <div class="input-box">
                    {{ form.gender }}
                    <label for="{{ form.gender.id_for_label }}"></label>
                    {{ form.gender.errors }}
                </div>
            </div>
            <div class="input-row">
                <div class="input-box">
                    {{ form.age }}
                    <label for="{{ form.age.id_for_label }}">Возраст</label>
                    {{ form.age.errors }}
                </div>
                <div class="input-box">
                    {{ form.tg_username }}
                    <label for="{{ form.tg_username.id_for_label }}">Ник в @Telegram</label>
                    {{ form.tg_username.errors }}
                </div>
            </div>
            <div class="input-row">
                <div class="input-box">
                    {{ form.username }}
                    <label for="{{ form.username.id_for_label }}">Имя пользователя</label>
                    {{ form.username.errors }}
                </div>
                <div class="input-box">
                    {{ form.email }}
                    <label for="{{ form.email.id_for_label }}"></label>
                    {{ form.email.errors }}
                </div>
            </div>
                <div class="input-row">
                    <div class="form-field">
                        <textarea id="interests" name="interests" maxlength="128" placeholder="Введите ваши интересы...">{{ form.interests.value|default:'' }}</textarea>
                        <label for="interests">Интересы</label>
                        {{ form.interests.errors }}
                    </div>
                    <div class="form-field">
                        <textarea id="additional_info" name="additional_info" maxlength="512" placeholder="Введите дополнительную информацию...">{{ form.additional_info.value|default:'' }}</textarea>
                        <label for="additional_info">Доп. информация</label>
                        {{ form.additional_info.errors }}
                    </div>
                </div>
            <button type="submit" class="btn">Сохранить изменения</button>
        </form>
    </div>
</div>

</html>

connect21/users/templates/users/registration.html
<!doctype html>
<html lang="en">

{% load static %}
<link rel="icon" href="{% static 'deps/images/favicon.svg' %}" type="image/x-icon">
<link rel="stylesheet" href="{% static 'deps/css/register_css.css' %}">
<title>{{ title }}</title>
<div class="container">
    <div class="login-box">
        <h2>Регистрация</h2>
        <form method="post" action="{% url 'users:register' %}">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="input-row">
                <div class="input-box">
                    {{ form.first_name }}
                    <label for="{{ form.first_name.id_for_label }}">Имя</label>
                    {{ form.first_name.errors }}
                </div>
                <div class="input-box">
                    {{ form.last_name }}
                    <label for="{{ form.last_name.id_for_label }}">Фамилия</label>
                    {{ form.last_name.errors }}
                </div>
            </div>
            <div class="input-row">
                <div class="input-box">
                    {{ form.surname }}
                    <label for="{{ form.surname.id_for_label }}">Отчество</label>
                    {{ form.surname.errors }}
                </div>
                <div class="input-box">
                    {{ form.gender }}
                    <label for="{{ form.gender.id_for_label }}"></label>
                    {{ form.gender.errors }}
                </div>
            </div>
            <div class="input-row">
                <div class="input-box">
                    {{ form.age }}
                    <label for="{{ form.age.id_for_label }}">Возраст</label>
                    {{ form.age.errors }}
                </div>
                <div class="input-box">
                    {{ form.tg_username }}
                    <label for="{{ form.tg_username.id_for_label }}">Ник в @Telegram</label>
                    {{ form.tg_username.errors }}
                </div>
            </div>
            <div class="input-row">
                <div class="input-box">
                    {{ form.username }}
                    <label for="{{ form.username.id_for_label }}">Имя пользователя</label>
                    {{ form.username.errors }}
                </div>
                <div class="input-box">
                    {{ form.email }}
                    <label for="{{ form.email.id_for_label }}">Электронная почта</label>
                    {{ form.email.errors }}
                </div>
            </div>
            <div class="input-row">
                <div class="input-box">
                    {{ form.password1 }}
                    <label for="{{ form.password1.id_for_label }}">Пароль</label>
                    {{ form.password1.errors }}
                </div>
                <div class="input-box">
                    {{ form.password2 }}
                    <label for="{{ form.password2.id_for_label }}">Подтверждение пароля</label>
                    {{ form.password2.errors }}
                </div>
            </div>
            <button type="submit" class="btn">Зарегистрироваться</button>
            <div class="signup-link">
                <a href="{% url 'users:login' %}">Уже есть аккаунт? Войти</a>
            </div>
        </form>
    </div>
</div>

</html>

connect21/users/templates/users/two_factor_auth.html
<!doctype html>
<html lang="en">

{% load static %}
<link rel="icon" href="{% static 'deps/images/favicon.svg' %}" type="image/x-icon">
<link rel="stylesheet" href="{% static 'deps/css/login_css.css' %}">
<title>{{ title }}</title>
<div class="container">
    <div class="login-box">
        <h2>Подтверждение кода</h2>
        <form method="post">
            {% csrf_token %}
            {% if form.non_field_errors %}
                <div class="error">
                    {% for error in form.non_field_errors %}
                        <p style="color: red;">{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="input-box">
                {{ form.code }}
                <label for="{{ form.code.id_for_label }}">Код подтверждения</label>
                {{ form.code.errors }}
            </div>
            <button type="submit" class="btn">Подтвердить</button>
        </form>
    </div>
</div>

</html>