connect21/community/urls.py
from django.urls import path

from .views import PublicProfileView, UserCommunityView, invite_user

app_name = 'community'

urlpatterns = [
    path('search/', UserCommunityView.as_view(), name='search'),
    path('@<str:username>/', PublicProfileView.as_view(), name='public-user-profile'),
    path('', UserCommunityView.as_view(), name='community-list'),
    path('invite/<int:user_id>/<int:group_id>/', invite_user, name='invite_user')

]

connect21/connect21/urls.py
from django.conf.urls import handler404
from django.contrib import admin
from django.urls import include, path

handler404 = 'main.views.page_not_found'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('community/', include('community.urls')),
    path('groups/', include('groups.urls'))

]

connect21/main/urls.py
from django.urls import path

from .views import AboutView, HomeView, RespondInvitationView

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    path('invite/respond/<int:invitation_id>/', RespondInvitationView.as_view(), name='respond_invitation'),
]

connect21/community/models.py
from django.db import models

# Create your models here.

connect21/community/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST
from django.views.generic import DetailView, ListView

from groups.models import ChatGroup, GroupMembership
from main.mixins import TitleMixin
from users.models import User

from .utils import check_and_invite_user, q_search


class UserCommunityView(TitleMixin, LoginRequiredMixin, ListView):
    title = 'Connect21 - Список пользователей'
    model = User
    template_name = 'community/community_list.html'
    context_object_name = 'users'
    paginate_by = 2
    allow_empty = False

    def get_queryset(self):
        queryset = User.objects.all().order_by('-username')
        query = self.request.GET.get('q')
        if query:
            return q_search(query)

        return queryset


class PublicProfileView(TitleMixin, LoginRequiredMixin, DetailView):
    model = User
    title = 'Connect21 - Профиль пользователя'
    template_name = 'community/public_profile.html'
    context_object_name = 'user_public_profile'

    def get_object(self, queryset=None):
        username = self.kwargs.get('username')
        return get_object_or_404(User, username=username)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_groups = GroupMembership.objects.filter(user=self.request.user).select_related('group')
        context['user_groups'] = [membership.group for membership in user_groups]
        return context


@login_required
@require_POST
def invite_user(request, user_id, group_id):
    try:
        invited_user = get_object_or_404(User, id=user_id)
        group = get_object_or_404(ChatGroup, id=group_id)

        if check_and_invite_user(request, invited_user, group):
            messages.success(request, f'Вы пригласили пользователя {invited_user.username} в чат')
        else:
            messages.warning(request, 'Пользователь является членом группы или уже был в нее приглашен.')

    except ObjectDoesNotExist:
        messages.warning(request, 'Пользователя или группы не существует.')
    except Exception as e:
        messages.warning(request, f'Непредвиденная ошибка: {str(e)}')

    return HttpResponseRedirect(request.META['HTTP_REFERER'])

connect21/community/templates/community/community_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="row">
        {% for user in users %}
            <div class="col-lg-4 col-md-6 p-4">
                <div class="card border-0 rounded custom-shadow">
                    <img src="{% if user.image %}{{ user.image.url }}{% else %}{% static 'deps/images/default_logo.webp' %}{% endif %}" alt="Аватар пользователя" class="card-img-top rounded-top">
                    <div class="card-body text-center">
                        <a href="{% url 'community:public-user-profile' username=user.username %}" class="card-link">
                            <h5 class="card-title custom-title">{{ user.username }}</h5>
                        </a>
                        <p class="card-text custom-text">Интересы: <span class="telegram-handle">{% if user.interests %}{{ user.interests }}{% else %}У пользователя пока нет интересов{% endif %}</span></p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center my-4">
            <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                <a class="page-link" href="?{% if page_obj.has_previous %}page={{ page_obj.previous_page_number }}{% endif %}">Назад</a>
            </li>

            {% for page in page_obj.paginator.page_range %}
                {% if page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
                    <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                        <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                <a class="page-link" href="?{% if page_obj.has_next %}page={{ page_obj.next_page_number }}{% endif %}">Следующая</a>
            </li>
        </ul>
    </nav>
{% endblock %}

connect21/community/templates/community/public_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="public_user_profile-profile-container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
        <div class="public_user_profile-card custom-shadow" style="width: 500px;">
            <img src="{% if user_public_profile.image %}{{ user_public_profile.image.url }}{% else %}{% static 'deps/images/default_logo.webp' %}{% endif %}" alt="Аватар пользователя" class="card-img-top rounded-top">
            <div class="public_user_profile-card-body text-center">
                <h5 class="card-title custom-title">{{ user_public_profile.first_name }} {{ user_public_profile.last_name }}</h5>
                <p class="card-text custom-text">Ник в Telegram: <span class="public_user_profile-telegram-handle">{{ user_public_profile.tg_username }}</span></p>
                <p class="card-text custom-text">Возраст: {{ user_public_profile.age }}</p>
                <p class="card-text custom-text">Интересы: {% if user_public_profile.interests %}{{ user_public_profile.interests }}{% else %}У пользователя пока нет интересов{% endif %}</p>
                <p class="card-text custom-text">Дополнительная информация: {% if user_public_profile.additional_info %}{{ user_public_profile.additional_info }}{% else %}У пользователя пока нет дополнительной информации{% endif %}</p>
                <h2 class=" custom-title">Пригласить в группу</h2>
                {% if user_groups %}
                    <ul class="list-group">
                        {% for group in user_groups %}
                            <li class="list-group-invite">
                                <form method="POST" action="{% url 'community:invite_user' user_public_profile.id group.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn_21 btn-primary">Пригласить в {{ group.name }}</button>
                                </form>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p class="card-text custom-text">Вы не состоите в группах, чтобы приглашать пользователей.</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}