connect21/community/urls.py
from django.urls import path

from .views import PublicProfileView, UserCommunityView, invite_user

app_name = 'community'

urlpatterns = [
    path('search/', UserCommunityView.as_view(), name='search'),
    path('@<str:username>/', PublicProfileView.as_view(), name='public-user-profile'),
    path('', UserCommunityView.as_view(), name='community-list'),
    path('invite/<int:user_id>/<int:group_id>/', invite_user, name='invite_user')

]

connect21/connect21/urls.py
from django.conf.urls import handler404
from django.contrib import admin
from django.urls import include, path

handler404 = 'main.views.page_not_found'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('community/', include('community.urls')),
    path('groups/', include('groups.urls'))

]

connect21/groups/urls.py
from django.urls import path

from .views import CreateGroupView, DeleteChatView, chat_view

app_name = 'groups'

urlpatterns = [
    path('chat/<uuid:group_uuid>/', chat_view, name='group_chat'),
    path('create/', CreateGroupView.as_view(), name='create_chat'),
    path('delete/<uuid:uuid>/', DeleteChatView.as_view(), name='delete_chat'),

]

connect21/main/urls.py
from django.urls import path

from .views import AboutView, HomeView, RespondInvitationView

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    path('invite/respond/<int:invitation_id>/', RespondInvitationView.as_view(), name='respond_invitation'),
]

connect21/users/urls.py
from django.urls import path

from .views import (CustomLoginView, CustomLogoutView, CustomProfileView,
                    CustomRegisterView, TwoFactorAuthView, forgot_password)

app_name = 'users'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', CustomRegisterView.as_view(), name='register'),
    path('profile/', CustomProfileView.as_view(), name='profile'),
    path('two-factor-auth/<uuid:uuid>', TwoFactorAuthView.as_view(), name='two-factor-auth'),
    path('forgot-password/', forgot_password, name='forgot-password'),
    path('logout/', CustomLogoutView.as_view(), name='logout')
]

connect21/templates/base.html
<!doctype html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'deps/css/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="icon" href="{% static 'deps/images/favicon.svg' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'deps/css/my_css.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">
    {% block css %}{% endblock %}
    <title>{% if title %}{{ title }}{% else %}Default Title{% endif %}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg custom-navbar">
            <div class="container">
                <a class="navbar-brand" href="{% url 'main:index' %}">
                    <img src="{% static 'deps/images/21logo.png' %}" alt="Connect21" class="logo-img">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white btn_21" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Информация
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#"><i class="bi bi-telephone"></i> Контактная информация</a></li>
                                <li><a class="dropdown-item" href="{% url 'main:about' %}"><i class="bi bi-info-circle"></i> Про нас</a></li>
                            </ul>
                        </li>
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="btn_21 nav-link" role="button" href="{% url 'users:login' %}"><i class="bi bi-person-fill"></i> Войти</a>
                            </li>
                        {% else %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white btn_21" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Мой профиль
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'users:profile' %}">Личный кабинет</a></li>
                                {% if user.is_admin or user.is_staff %}
                                <li><a class="dropdown-item" href="{% url 'admin:index' %}">Админ панель</a></li>
                                {% endif %}
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
                            </ul>
                        </li>
                            {% if show_create_chat_button %}
                            <a href="{% url 'groups:create_chat' %}" class="btn_21 create-chat-btn nav-link" role="button">Создать чат</a>
                            {% endif %}
                        {% endif %}
                    </ul>
                    <form class="d-flex search-form" role="search" action="{% url 'community:search' %}" method="get">
                        <input class="form-control me-2 custom-search search-input" type="search" name="q" placeholder="Найти пользователя" aria-label="Search">
                        <button class="btn_21 search" type="submit">
                            <i class="bi bi-search"></i>
                        </button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-10 offset-lg-1">
                    {% include 'includes/notifications.html' %}
                    {% block content %} {% endblock %}
                </div>
            </div>
        </div>
    </section>
    <script src="{% static 'deps/js/jquery/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'deps/js/bootstrap/bootstrap.bundle.min.js' %}"></script>
</body>

</html>